name: update_env_infrustructure

on:
  workflow_dispatch:
    inputs:
      dispatch_id:
        description: 'A unique ID provided when dispatching this workflow'
        required: false
        type: string
      environment_name: 
        description: 'Name of the environment'
        required: true
        type: string  

jobs:  
  dispatch-id:
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.dispatch_id != ''
    runs-on: [ ubuntu-latest ]
    steps:
      - id: dispatch-id
        name: ${{ github.event.inputs.dispatch_id }}
        run: echo "The dispatch ID is ${{ github.event.inputs.dispatch_id }}"

  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    environment: 
      name: ${{ github.event.inputs.environment_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false      

      - name: Terraform Init
        id: init
        run: terraform init --backend-config="resource_group_name=rg-infrastructure-${{ github.event.inputs.environment_name }}" --backend-config="storage_account_name=infrastatic${{ github.event.inputs.environment_name }}" --backend-config="container_name=terraformstatefiles" --backend-config="key=${{ vars.AZ_ENV_NAME }}-${{ github.event.inputs.environment_name }}-${{ vars.AZ_ENV_SUFIX }}" 
        env:        
          TF_VAR_ARM_CLIENT_ID: ${{secrets.AZ_CLIENT_ID}}
          TF_VAR_ARM_CLIENT_SECRET: ${{secrets.AZ_CLIENT_SECRET}}
          TF_VAR_ARM_SUBSCRIPTION_ID: ${{secrets.AZSUBSCRIPTION_ID}}
          TF_VAR_ARM_TENANT_ID: ${{secrets.AZ_TENANT_ID}} 

          TF_VAR_az_env_name: ${{ vars.AZ_ENV_NAME }}
          TF_VAR_az_env_sufix: ${{ vars.AZ_ENV_SUFIX }}
              
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color 
        env:
          TF_VAR_az_env_name: ${{ vars.AZ_ENV_NAME }}
          TF_VAR_az_env_sufix: ${{ vars.AZ_ENV_SUFIX }}

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -input=false 
        continue-on-error: true  
        env:
          TF_VAR_az_env_name: ${{ vars.AZ_ENV_NAME }}
          TF_VAR_az_env_sufix: ${{ vars.AZ_ENV_SUFIX }}

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply        
        run: terraform apply -auto-approve -input=false
        env:
          TF_VAR_az_env_name: ${{ vars.AZ_ENV_NAME }}
          TF_VAR_az_env_sufix: ${{ vars.AZ_ENV_SUFIX }}
