name: update_ca_image

on:
  repository_dispatch:
    types: [update-ca-workflow]    

jobs:  
  update-ca-image:
    runs-on: [ ubuntu-latest ]
    steps:
      - id: test
        run: echo "Action was triggered! ca=${{ github.event.client_payload.ca_name }} image=${{ github.event.client_payload.ca_image }}"